# This is a placeholder file for the twilight branch. The real workflow can be found there!

name: Update Twilight AVX2 AUR Package - zen-twilight-avx2-bin

on:
  workflow_dispatch:

jobs:
  aur-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "Hello World!"
